# Generated by Django 2.1.7 on 2019-03-18 20:41

import SpeechToText.models
import SpeechToText.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Transcript', models.TextField(null=True)),
                ('UploadedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Content', models.FileField(blank=True, null=True, upload_to=SpeechToText.models.scramble_uploaded_filename, validators=[SpeechToText.validators.validate_file_extension], verbose_name='UploadedFiles')),
                ('Comment', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpeechToText.FileType'),
        ),
        migrations.AddField(
            model_name='file',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
