# Generated by Django 2.1.7 on 2019-03-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechToText', '0009_auto_20190306_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
